
sudo: required
language: java

jdk:
  - openjdk8

script:
  - ./gradlew build -x test

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/galilasmb/jFSTMerge/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-62faf1bf32e1a07a971e56c8a3de8ae33988839e
  file_glob: true
  overwrite: false
  skip_cleanup: true
  on:
    all_branches: true 
            